server:
  port: 8080

spring:
  application:
    name: stp-mvp
  profiles:
      active: dev

  r2dbc:
    url: r2dbc:postgresql://dev-pghost:5432/stm
    username: postgres
    password: changeme
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    org.springframework.r2dbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


app:
  client:
    http:
      services:
        serviceA:
          url: "https://jsonplaceholder.typicode.com/posts/1"
          token: ${TOKEN:default-token-if-not-set}

